package com.xpwnit.dualbt.audio;

public final class CalibrationToneTest {
    public static void main(String[] args) {
        generatesStereoPcmForRequestedDuration();
        clampsUnsafeGainValues();
    }

    private static void generatesStereoPcmForRequestedDuration() {
        byte[] pcm = CalibrationTone.stereoSinePcm(48_000, 1_000, 660.0, 0.5);

        assertEquals(48_000 * 4, pcm.length, "one second of stereo PCM16 should be generated");
        assertTrue(containsNonZeroSample(pcm), "tone should contain non-zero samples");
        assertEquals(pcm[0], pcm[2], "left and right low bytes should match");
        assertEquals(pcm[1], pcm[3], "left and right high bytes should match");
    }

    private static void clampsUnsafeGainValues() {
        byte[] pcm = CalibrationTone.stereoSinePcm(8_000, 250, 440.0, 3.0);

        assertEquals(8_000, pcm.length, "duration should control generated byte count");
        assertTrue(maxAbsSample(pcm) <= 32_767, "samples must stay inside signed 16-bit range");
    }

    private static boolean containsNonZeroSample(byte[] pcm) {
        for (byte value : pcm) {
            if (value != 0) {
                return true;
            }
        }
        return false;
    }

    private static int maxAbsSample(byte[] pcm) {
        int max = 0;
        for (int i = 0; i + 1 < pcm.length; i += 2) {
            int sample = (pcm[i] & 0xFF) | (pcm[i + 1] << 8);
            max = Math.max(max, Math.abs(sample));
        }
        return max;
    }

    private static void assertTrue(boolean value, String message) {
        if (!value) {
            throw new AssertionError(message);
        }
    }

    private static void assertEquals(int expected, int actual, String message) {
        if (expected != actual) {
            throw new AssertionError(message + ": expected " + expected + " but got " + actual);
        }
    }
}
